### ISSUE TITLE
react vendor files

### ISSUE THREAD

**Issue by acornejo** [tcoopman/react-es6-browserify#4]
react is not part of the vendor files, it is bundled.

on the other hand, react is listed as a bower component in the gulpfile, and bower isn't even a part of this repository (I prefer npm myself).

**Comment by tcoopman** [comment]
If you write a pull request, I'm happy to merge it. I won't fix this myself as I don't use browserify anymore. Switched to webpack.

**Comment by badsyntax** [comment]
I noticed similar problems when attempting to use this project. I intended to send PR's, but I decided to go the webpack route as well. I ended up creating https://github.com/badsyntax/react-seed which is inspired by this project.

**Comment by tcoopman** [comment]
Nice, I have a similar project that I do maintain: https://github.com/tcoopman/boilerplate-webpack-react
