### ISSUE TITLE
A yeoman generator

### ISSUE THREAD

**Issue by puranjayjain** [tcoopman/react-es6-browserify#6]
@tcoopman nice effort but I was wondering if we could have a [yeoman](http://yeoman.io/) generator for this boilerplate. it would be a wonderful addition to this awesome component. What do you think? should we have a separate repository for this or do it in this one. I'll be happy to add a pr or a new repo via a fork. Please respond with your thoughts.

**Comment by tcoopman** [comment]
I don't use browserify anymore, so this repository is not really maintained. That said, feel free to fork and implement the generator.
